### ISSUE TITLE
bug: smoke testing of infra running in CI

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#169]
## Overview
Running the CI for `cosmos-sdk` seems to failing in 1 out of 5 runs. The infra setup seems to just timeout.

We need to run the CI more often and figure out actual issues.

> Note: In the CI, the resources are limted, hence k8s might not also be able to heal the system. Smoke tests against a k8s cluster seems to work fine so far.

## Proposal
1. run more smoke tests to find out the actual number of transient failures (both in the CI and locally)
2. logs and `kubectl describe pods` should be added in `starship-action` for debugging the reason of failures in the CI

## Possible fixes
1. Provide more resource with limits and request (2nd node could be consuming more resources than the first)
2. Add automated retries for infra spinup, or action on failure

## Affected Clients
https://github.com/cosmos/cosmos-sdk/actions/workflows/starship-tests.yml

## Todos

- [x] cosmology-tech/starship-action/issues/14
- [x] cosmology-tech/starship-action/issues/15
- [x] cosmology-tech/starship/issues/170

## Fixes
- [ ] cosmology-tech/starship/issues/172

**Comment by Anmol1696** [comment]
Reason for validator-0 failure after the genesis node is created, is around the `postStartHook` which creates the validator itself.
Multiple validator nodes done seem to self healing, and get stuck in `CrashLoopBackOff`, which does not happen offten.

We need a better long term solution for this, but the retry seems to be working well for now.

**Comment by Anmol1696** [comment]
Closing this, since smoke tests have been added properly. The bug is still persistent and is tracked in a seperate issue.
