### ISSUE TITLE
EPIC: Mesh-security (OGP)

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship#174]
Mesh security integration is the highest priority. As part of OGP grant (M2) milestone

## Work Breakdown
- [x] integrate starship into `mesh-security-sdk` repo
- [ ] https://github.com/cosmology-tech/starship/issues/157
- [x] https://github.com/cosmology-tech/starship/issues/153
- [x] figure out good abstraction for instantiating contracts for the mesh
- [ ] write more test cases
- [ ] https://github.com/cosmology-tech/starship/issues/141

## Work in Progress:
- [ ] https://github.com/cosmology-tech/starship/pull/143
- [x] https://github.com/osmosis-labs/mesh-security-sdk/pull/56

## Todos
- [x] https://github.com/cosmology-tech/starship/issues/106
- [x] https://github.com/osmosis-labs/mesh-security-sdk/issues/53
- [x] https://github.com/osmosis-labs/mesh-security-sdk/issues/62

## Notes
Starship would need to become more robust to be able to handle future requirements for Mesh Security

**Comment by Anmol1696** [comment]
Completed OGP 1
